#version: '3'
#
#services:
#  nginx:
#    image: nginx:latest
#    ports:
#    - 8080:8080
#    volumes:
#    - /root/nginx/html:/usr/share/nginx/html
#    - /root/nginx/nginx.conf:/etc/nginx/nginx.conf
#    privileged: true
#  mysql:
#    image: mysql:8.0.23
#    ports:
#    - 3306:3306
#    environment:
#      - MYSQL_ROOT_PASSWORD=123456
#  redis:
#    image: redis:5.0.3
#  blog:
#    image: blog:latest
#    build: .
#    ports:
#    - 8081:8081
#    depends_on:
#      - mysql
#      - redis